version: "3"

services:
  cocalc:
    container_name: cocalc
    restart: unless-stopped
    image: cocalc-melashri
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "NOSSL=true"
    volumes:
      - ${DATA_DIR}:/projects
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - "${PORT}:80"
    networks:
      - npm

networks:
  npm:
    name: npm_network      